[package]
name = "rust-adb-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.4"
num-bigint-dig = "0.8.2"
rand = "0.8.5"
rcgen = "0.11.1"
rsa = "0.9.2"
sha1 = "0.10.5"
