[package]
name = "fdevent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
libc = "0.2.147"
log = "0.4.20"
mio = { version = "0.8.8", features = ["os-poll", "net"] }
thiserror = "1.0.44"

[dev-dependencies]
env_logger = "0.10.0"
tempfile = "3.8.0"
